
 services:
  backend:
    build:
      context: ./ttd-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mappt den Port 3000 des Containers auf den Port 3000 des Hosts
    environment:
      - FLASK_ENV=development # Beispiel für Umgebungsvariablen
    volumes:
      - ./ttd-backend:/app
    
  
  frontend:
    build:
      context: ./ttd-frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Mappt den Port 5000 des Containers auf den Port 5000 des Hosts
    volumes:
      - ./ttd-frontend:/app
    depends_on:
      - backend # Frontend startet, nachdem das Backend bereit is