FROM nginx:alpine

COPY index.html /usr/share/nginx/html
COPY style.css /usr/share/nginx/html
COPY script.js /usr/share/nginx/html
COPY functions.js /usr/share/nginx/htmal
COPY nginx.conf /etc/nginx/nginx.conf

